[WIP] All or Nothing Auth
BD2KGenomics/boardwalk pull request #91
Opened 2018-09-27 10:12 UTC by NoopDog

2018-09-27 10:15 UTC, NoopDog commented
@coverbeck this is not ready to merge but I wanted to let you know we are deep into getting this going. We updated the HTTPClient to the newer API along the way. We need to test as all of the DAOs have changed and we also need to remove the flash of the BW screen with no data before the auth wall shows. Picking this up agin in our morning and expect to be through it for your Friday am.

2018-09-27 17:10 UTC, coverbeck commented
@NoopDog Just curious, are you able to log in from your locally running UI using `https://jesse.ucsc-cgp-dev.org/` as the backend? I would think not, but maybe you've discovered a way, and I'm going down the wrong road in https://ucsc-cgl.atlassian.net/browse/TLP-559.

The first issue would be that the backend is only issuing cookies with the secure attribute set, so unless your local UI is on https I don't think it will work.

2018-10-05 11:55 UTC, NoopDog commented
HI @coverbeck I have rebased on feature/commons and am submitting the PR. Can you push this to the "Charles" test instance and if it looks ok merge this into feature commons? 

Cheers and Thanks, D

2018-10-05 17:18 UTC, coverbeck requested changes
In addition to the 403 redirect comments, I think your copyright messages should say CGP, not CGL, and point to https://cgp.genomics.ucsc.edu, although it's not a big deal if you keep it.

CGL = Wet lab stuff
CGP = Computational stuff

2018-10-05 17:18 UTC, coverbeck commented on spa/src/app/auth/error.interceptor.ts
> +                    this.router.navigateByUrl("/register");
Could you redirect to `/unauthorized` instead? Or better yet, if it's not a hassle, `/unauthorized?account=<redacted email>`.

The problem is that we have the contact email configurable, via a property, and the currently configured value doesn't match your hard-coded email in register.component.html.

Our options are 

1. Change the hard-coded email in here to match the configured email, and update the source code every time it changes.
2. Surface the configured email via an API so you can display it dynamically
3. Just redirect to `/unauthorized`.

I think it's easiest to just do 3, and you can fix up that page in the Gatsby work, which will then apply to both being invoked from here and when an unauthorized user tries to log-in.

2018-10-05 17:18 UTC, coverbeck commented on spa/src/app/auth/register/register.component.html
> +        To register for data access, please contact <a href="mailto:casloan@ucsc.edu">casloan@ucsc.edu</a>.
See my above comment... I think it would best not to have this email merged into the main branch as well, as it might get harvested.

2018-10-05 17:18 UTC, coverbeck commented on spa/src/app/data/user/user.service.ts
> +    public downloadRedwoodToken(): Observable<boolean> {
This method can be removed if you want -- since Commons Boardwalk uses Blue Box and Azul, there is no longer Redwood.

Or you could just leave it for a future PR.

2018-10-05 17:28 UTC, coverbeck commented
My comment about CGL being a wet lab was wrong; it is dry lab research. That said I still think you should CGP, as that is our team. Again, not a big deal.

2018-10-09 11:39 UTC, NoopDog commented on spa/src/app/auth/error.interceptor.ts
> +                    this.router.navigateByUrl("/register");
Ok redirecting to /unauthorized for now.

2018-10-09 11:40 UTC, NoopDog commented on spa/src/app/auth/register/register.component.html
> +        To register for data access, please contact <a href="mailto:casloan@ucsc.edu">casloan@ucsc.edu</a>.
will delete.

2018-10-09 11:54 UTC, NoopDog commented
Hi @coverbeck I believe I have addressed your PR comments. Please take a look. If If you can deploy to  the your server as well we can test this out and merge if it looks ok

2018-10-09 16:17 UTC, coverbeck requested changes

2018-10-09 16:17 UTC, coverbeck commented on spa/src/app/auth/error.interceptor.ts
> +                    this.document.location.replace(`${rootUrl}/unathorized`);
Typo in `unauthorized`

2018-10-09 18:15 UTC, NoopDog commented on spa/src/app/auth/error.interceptor.ts
> +                    this.document.location.replace(`${rootUrl}/unathorized`);
This should be addressed.. thanks!

2018-10-09 18:16 UTC, NoopDog commented
@coverbeck the URL typo should be addressed

2018-10-09 18:39 UTC, coverbeck approved these changes

2018-10-09 18:55 UTC, merged